version: '2'
services:

  mongo:
    restart: always
    image: mongo
    ports:
     - "27017:27017"

  redis:
    restart: always
    image: "redis"
    ports:
     - "6379:6379"

  rabbit:
    restart: always
    image: rabbitmq:3.6.0-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
