---
spring:
  profiles: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fernandofazolli/ecommerce-config
  application:
    name: config

server:
  port: 8001